# Generated by Django 5.0.6 on 2024-07-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_blog_category_comment_gallery_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('cover_image', models.ImageField(upload_to='book_cover/]')),
                ('spine_image', models.ImageField(upload_to='book_spine/')),
                ('publisher', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('pages', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
