# Generated by Django 5.0.6 on 2024-07-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_book_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='cover_image',
            new_name='kitobni_oldi',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='spine_image',
            new_name='kitobni_yoni',
        ),
    ]
