# Generated by Django 5.0.6 on 2024-07-25 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_rename_cover_image_book_kitobni_oldi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='kitobni_oldi',
            new_name='cover_image',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='kitobni_yoni',
            new_name='spine_image',
        ),
    ]
