# Generated by Django 5.0.6 on 2024-07-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_rename_kitobni_oldi_book_cover_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Images/About')),
                ('title', models.CharField(max_length=50)),
                ('About_me', models.TextField()),
            ],
        ),
    ]
