# Generated by Django 5.0.6 on 2024-07-25 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_about_me'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About_me',
        ),
    ]
