# Generated by Django 5.0.6 on 2024-07-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_blog_alter_book_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Images/about')),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField()),
            ],
        ),
    ]
