# Generated by Django 5.0.6 on 2024-07-31 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='PortfolioCategory',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='categorys',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfoliocategory'),
            preserve_default=False,
        ),
    ]
